configuration-as-code: {
  }
credentials:
  blueOcean: {
    }
  folder: {
    }
  providerImpl: {
    }
  system:
    domainCredentials:
    - credentials:
      - usernamePassword:
          id: "8c4076a6-d44c-4a88-9090-fcfef2c959a6"
          password: "{AQAAABAAAAAQRM2A5k2mGMWsVxubsOtj3mJ6R2WPX6HLfZCEDkTrmtk=}"
          scope: GLOBAL
          username: "jenkins"
      domain: {
        }
  user: {
    }
jenkins:
  authorizationStrategy:
    loggedInUsersCanDoAnything:
      allowAnonymousRead: false
  clouds:
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "tcp://10.0.0.151:4243"
        readTimeout: 60
      errorDuration: 30
      exposeDockerHost: true
      name: "jagent01"
      templates:
      - connector:
          ssh:
            sshKeyStrategy:
              manuallyConfiguredSSHKey:
                credentialsId: "8c4076a6-d44c-4a88-9090-fcfef2c959a6"
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "builder-amd64"
          mounts:
          - "type=bind,source=/srv/nfs_share,dst=/home/jenkins"
          mountsString: "type=bind,source=/srv/nfs_share,dst=/home/jenkins"
        instanceCapStr: "5"
        labelString: "builder-amd64"
        name: "builder-amd64"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
        remoteFs: "/home/jenkins"
  - docker:
      dockerApi:
        connectTimeout: 30
        dockerHost:
          uri: "tcp://10.0.0.152:4243"
        readTimeout: 60
      errorDuration: 30
      exposeDockerHost: true
      name: "jagent02"
      templates:
      - connector:
          ssh:
            sshKeyStrategy:
              manuallyConfiguredSSHKey:
                credentialsId: "8c4076a6-d44c-4a88-9090-fcfef2c959a6"
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "builder-amd64:latest"
          mounts:
          - "type=bind,source=/srv/nfs_share,dst=/home/jenkins"
          mountsString: "type=bind,source=/srv/nfs_share,dst=/home/jenkins"
        instanceCapStr: "5"
        labelString: "builder-amd64"
        name: "builder-amd64"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
        remoteFs: "/home/jenkins"
  - docker:
      dockerApi:
        connectTimeout: 60
        dockerHost:
          uri: "tcp://10.0.0.153:4243"
        readTimeout: 60
      errorDuration: 30
      exposeDockerHost: true
      name: "jagent03"
      templates:
      - connector:
          ssh:
            sshKeyStrategy:
              manuallyConfiguredSSHKey:
                credentialsId: "8c4076a6-d44c-4a88-9090-fcfef2c959a6"
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "builder-amd64:latest"
          mounts:
          - "type=bind,source=/srv/nfs_share,dst=/home/jenkins"
          mountsString: "type=bind,source=/srv/nfs_share,dst=/home/jenkins"
        instanceCapStr: "5"
        labelString: "builder-amd64"
        name: "builder-amd64"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
        remoteFs: "/home/jenkins"
      - connector:
          ssh:
            sshKeyStrategy:
              manuallyConfiguredSSHKey:
                credentialsId: "8c4076a6-d44c-4a88-9090-fcfef2c959a6"
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "builder-i386"
          mounts:
          - "type=bind,source=/srv/nfs_share,dst=/home/jenkins"
          mountsString: "type=bind,source=/srv/nfs_share,dst=/home/jenkins"
        instanceCapStr: "5"
        labelString: "builder-i386"
        name: "builder-i386"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
        remoteFs: "/home/jenkins"
      - connector:
          ssh:
            sshKeyStrategy:
              manuallyConfiguredSSHKey:
                credentialsId: "8c4076a6-d44c-4a88-9090-fcfef2c959a6"
                sshHostKeyVerificationStrategy: "nonVerifyingKeyVerificationStrategy"
        dockerTemplateBase:
          cpuPeriod: 0
          cpuQuota: 0
          image: "builder-arm64v8"
        instanceCapStr: "5"
        labelString: "builder-arm64v8"
        name: "builder-arm64v8"
        pullStrategy: PULL_NEVER
        pullTimeout: 300
        remoteFs: "/home/jenkins"
  crumbIssuer:
    standard:
      excludeClientIPFromCrumb: false
  disableRememberMe: false
  disabledAdministrativeMonitors:
  - "jenkins.security.csp.impl.CspRecommendation"
  - "jenkins.diagnostics.ControllerExecutorsAgents"
  labelAtoms:
  - name: "builder-amd64"
  - name: "builder-arm64v8"
  - name: "builder-i386"
  - name: "built-in"
  log: {
    }
  markupFormatter: "plainText"
  mode: NORMAL
  nodeMonitors:
  - "architecture"
  - "clock"
  - diskSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "swapSpace"
  - tmpSpace:
      freeSpaceThreshold: "1GiB"
      freeSpaceWarningThreshold: "2GiB"
  - "responseTime"
  numExecutors: 2
  primaryView:
    all:
      name: "all"
  projectNamingStrategy: "standard"
  quietPeriod: 5
  remotingSecurity:
    enabled: true
  scmCheckoutRetryCount: 0
  securityRealm:
    local:
      allowsSignup: false
      enableCaptcha: false
      users:
      - id: "admin"
        name: "Thomas F Sandholm"
        properties:
        - theme:
            theme: "noOp"
        - "consoleUrlProvider"
        - "viewsTabBar"
        - "favorite"
        - myView:
            viewsTabBar: "standard"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
        - mailer:
            emailAddress: "tom.sandholm@gmail.com"
        - "apiToken"
      - id: "jenkins"
        name: "Thomas Sandholm"
        properties:
        - theme:
            theme: "noOp"
        - "apiToken"
        - "consoleUrlProvider"
        - "viewsTabBar"
        - "favorite"
        - myView:
            viewsTabBar: "standard"
        - preferredProvider:
            providerId: "default"
        - "timezone"
        - "experimentalFlags"
        - mailer:
            emailAddress: "tom.sandholm@gmail.com"
  slaveAgentPort: 50000
  updateCenter:
    sites:
    - id: "default"
      url: "https://updates.jenkins.io/update-center.json"
  views:
  - all:
      name: "all"
  viewsTabBar: "standard"
globalCredentialsConfiguration:
  configuration:
    providerFilter: "none"
    typeFilter: "none"
appearance:
  consoleUrlProvider: {
    }
  pipelineGraphView:
    showGraphOnBuildPage: false
    showGraphOnJobPage: false
    showStageDurations: false
    showStageNames: false
  prism:
    theme: PRISM
  themeManager:
    disableUserThemes: false
    theme: "noOp"
security:
  apiToken:
    creationOfLegacyTokenEnabled: false
    tokenGenerationOnCreationEnabled: false
    usageStatisticsEnabled: true
  apiTokenProperty: {
    }
  contentSecurityPolicy:
    enforce: false
  copyartifact:
    mode: PRODUCTION
  cps:
    hideSandbox: false
  crumb: {
    }
  gitHooks:
    allowedOnAgents: false
    allowedOnController: false
  gitHostKeyVerificationConfiguration:
    sshHostKeyVerificationStrategy: "knownHostsFileVerificationStrategy"
  globalJobDslSecurityConfiguration:
    useScriptSecurity: true
  prism:
    protectSourceCodeByPermission: false
  queueItemAuthenticator: {
    }
  scriptApproval:
    forceSandbox: false
  updateSiteWarningsConfiguration: {
    }
unclassified:
  administrativeMonitorsConfiguration: {
    }
  artifactManager: {
    }
  bitbucketEndpointConfiguration:
    endpoints:
    - bitbucketCloudEndpoint:
        enableCache: false
        repositoriesCacheDuration: 0
        teamCacheDuration: 0
        webhook:
          cloudWebhook:
            enableHookSignature: false
            manageHooks: false
  buildDiscarders:
    configuredBuildDiscarders:
    - "jobBuildDiscarder"
  buildStepOperation:
    enabled: false
  buildUser: {
    }
  buildUserVars:
    allBuilds: false
  casCGlobalConfig: {
    }
  computerRetentionCheckInterval: {
    }
  defaultDisplayUrlProvider: {
    }
  defaultFolderConfiguration: {
    }
  defaultView: {
    }
  email-ext:
    adminRequiredForTemplateTesting: false
    allowUnregisteredEnabled: false
    charset: "UTF-8"
    debugMode: false
    defaultBody: |-
      $PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS:

      Check console output at $BUILD_URL to view the results.
    defaultSubject: "$PROJECT_NAME - Build # $BUILD_NUMBER - $BUILD_STATUS!"
    defaultTriggerIds:
    - "hudson.plugins.emailext.plugins.trigger.FailureTrigger"
    mailAccount: {
      }
    maxAttachmentSize: -1
    maxAttachmentSizeMb: -1
    precedenceBulk: false
    throttlingEnabled: false
    watchingEnabled: false
  enrichedSummaryConfig:
    enrichedSummaryEnabled: false
    httpClientDelayBetweenRetriesInSeconds: 1
    httpClientMaxRetries: 3
    httpClientTimeoutInSeconds: 1
  envVarsFilter: {
    }
  fingerprints:
    fingerprintCleanupDisabled: false
    storage: "file"
  gitHubConfiguration:
    apiRateLimitChecker: ThrottleForNormalize
  gitHubPluginConfig:
    hookUrl: "http://jendock.tsand.org:8080/github-webhook/"
  globalConfigFiles: {
    }
  globalDefaultFlowDurabilityLevel: {
    }
  globalLibraries: {
    }
  globalTimeOutConfiguration:
    operations:
    - "abortOperation"
    overwriteable: false
  globalUntrustedLibraries: {
    }
  injectionConfig:
    allowUntrusted: false
    checkForBuildAgentErrors: false
    enabled: false
    enforceUrl: false
    injectCcudExtension: false
    injectMavenExtension: false
  junitTestResultStorage:
    storage: "file"
  location:
    adminAddress: "address not configured yet <nobody@nowhere>"
    url: "http://jendock.tsand.org:8080/"
  mailer:
    charset: "UTF-8"
    useSsl: false
    useTls: false
  metricsAccessKey: {
    }
  myView: {
    }
  nodeProperties: {
    }
  pipeline-model-docker: {
    }
  plugin: {
    }
  pollSCM:
    pollingThreadCount: 10
  projectNamingStrategy: {
    }
  proxyConfigurationManager: {
    }
  quietPeriod: {
    }
  resourceRoot: {
    }
  scmGit:
    addGitTagAction: false
    allowSecondFetch: false
    createAccountBasedOnEmail: false
    disableGitToolChooser: false
    hideCredentials: false
    showEntireCommitSummaryInChanges: false
    useExistingAccountWithSameEmail: false
  scmRetryCount: {
    }
  shell: {
    }
  timestamper:
    allPipelines: false
    elapsedTimeFormat: "'<b>'HH:mm:ss.S'</b> '"
    systemTimeFormat: "'<b>'HH:mm:ss'</b> '"
  upstream:
    globalUpstreamFilterStrategy: UseOldest
  usageStatistics: {
    }
  viewsTabBar: {
    }
tool:
  git:
    installations:
    - home: "git"
      name: "Default"
  mavenGlobalConfig:
    globalSettingsProvider: "standard"
    settingsProvider: "standard"
