#! /bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:
# this will start the new jenkins docker container, and will use a volume from /var/lib/jenkins to
# /var/jenkins_home in the container.  This way your settings and plugins are saved in the host
# volume, the restart will ensure the jenkins stays running.
#docker run --name jenkins-controller -d -v /var/lib/jenkins:/var/jenkins_home -p 8080:8080 -p 50000:50000 --restart=on-failure custom-jenkins-docker
docker run --name jenkins-controller -d -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/jenkins:/var/jenkins_home -p 8080:8080 -p 50000:50000 --restart=on-failure custom-jenkins-docker

