#! /bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:

SERVER="http://jendock.tsand.org:8080"
AUTH="jenkins:jenkins"

java -jar ./jenkins-cli.jar -auth $AUTH -s ${SERVER} list-plugins
