#! /bin/bash
# vi:set nu ai ap aw smd showmatch tabstop=4 shiftwidth=4:

SERVER="http://jendock.tsand.org:8080"
TOKEN="11cd9b42c2299b18f9d29fef66e653f21a"
AUTH="jenkins:${TOKEN}"


java -jar ./jenkins-cli.jar -auth $AUTH -s ${SERVER} restart
